---
stages:
  - unit tests
  - build
  - docker build
  - integration tests
  - docker release

image: golang:1.11.5

variables:
  _GOTAGS: "run_rockpaperscissors run_inmemory"

go:unit tests:
  stage: unit tests
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
  script:
    - go test ./... -tags="${_GOTAGS}" -coverpkg=./... -coverprofile=cover.out
    - go tool cover -func=cover.out

go:build:
  stage: build
  before_script:
    - cd $GOPATH/src
    - ln -s $CI_PROJECT_DIR $CI_PROJECT_NAME
    - cd $CI_PROJECT_NAME
  script:
    - CGO_ENABLED=0 GOOS=linux go build -tags="${_GOTAGS}" -o dist/backend/$CI_PROJECT_NAME
    - CGO_ENABLED=0 GOOS=windows go build -tags="${_GOTAGS}" -o dist/backend/$CI_PROJECT_NAME.exe
  artifacts:
    paths:
      - dist/
  dependencies:
    - go:unit tests

docker:build:backend:
  stage: docker build
  services:
    - docker:dind
  image: docker:git
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  dependencies:
    - go:build

bash:helpers:integration tests:
  stage: integration tests
  services:
    - docker:dind
  image: docker
  variables:
    PLATEAU_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    BASH_ASSERT_IMAGE: $CI_REGISTRY/le-garff-yoann/docker-bash-assert
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker pull $PLATEAU_IMAGE
    - docker pull $BASH_ASSERT_IMAGE
    - >
      docker run -d --name plateau
      $PLATEAU_IMAGE
      run -l :3000 --session-key s
    - sleep 10
    - >
      docker run -d --link plateau --name assert
      --entrypoint sleep
      $BASH_ASSERT_IMAGE
      300
    - |
      for f in *.bash
      do
        docker cp $f assert:/tmp
      done
    - >
      docker exec
      -w /tmp
      -e TPG_PLATEAU_BASEURL=http://plateau:3000
      assert
      bash helpers_test.bash
  dependencies:
    - docker:build:backend

docker:release:backend:
  stage: docker release
  services:
    - docker:dind
  image: docker:git
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  dependencies:
    - go:build
    - bash:helpers:integration tests
  only:
    - tags
