package event

// Event ...
type Event string

const (
	// EInternalError ...
	EInternalError Event = "INTERNAL_ERROR"
	// EProcessed ...
	EProcessed Event = "PROCESSED"
	// EIllegal ...
	EIllegal Event = "ILLEGAL"
	// EListEvents ...
	EListEvents Event = "LIST"
	// EGameWantToStart ...
	EGameWantToStart Event = "GAME_WANT_TO_START"
	// EGameStarts ...
	EGameStarts Event = "GAME_STARTS"
	// EGameEnds ...
	EGameEnds Event = "GAME_ENDS"
	// EPlayerConnects ...
	EPlayerConnects Event = "PLAYER_CONNECTS"
	// EPlayerDisconnects ...
	EPlayerDisconnects Event = "PLAYER_DISCONNECTS"
	// EPlayerReconnects ...
	EPlayerReconnects Event = "PLAYER_RECONNECTS"
	// EPlayerWantToJoin ...
	EPlayerWantToJoin Event = "PLAYER_WANT_TO_JOIN"
	// EPlayerJoins ...
	EPlayerJoins Event = "PLAYER_JOINS"
	// EPlayerWantToLeave ...
	EPlayerWantToLeave Event = "PLAYER_WANT_TO_LEAVE"
	// EPlayerLeaves ...
	EPlayerLeaves Event = "PLAYER_LEAVES"
	// EPlayerWantToSurrender ...
	EPlayerWantToSurrender Event = "PLAYER_WANT_TO_SURRENDER"
	// EPlayerSurrenders ...
	EPlayerSurrenders Event = "PLAYER_SURRENDERS"
)

func (s Event) String() string {
	return string(s)
}
