version: "3"

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${PLATEAU_LISTEN_PORT:-80}:80"
    depends_on:
      - plateau
    command: [ nginx, "-g", "daemon off;" ]
    restart: unless-stopped

  plateau:
    build:
      context: ..
      dockerfile: docker/plateau/Dockerfile
      args:
        GO_TAGS: "run_${PLATEAU_GO_GAME_TAG:-rockpaperscissors} run_postgresql"
    depends_on:
      - postgresql
    command:
      - run
      - -l
      - :80
      - --session-key
      - "${PLATEAU_SESSION_KEY:?Requires $PLATEAU_SESSION_KEY}"
      - --pg-url
      - "postgresql://${PLATEAU_POSTGRES_USER:-pg}:${PLATEAU_POSTGRES_PASSWORD:-pg}@postgresql/${PLATEAU_POSTGRES_USER:-pg}?sslmode=disable"
    restart: unless-stopped

  postgresql:
    image: postgres:12
    environment:
      POSTGRES_USER: "${PLATEAU_POSTGRES_USER:-pg}"
      POSTGRES_PASSWORD: "${PLATEAU_POSTGRES_PASSWORD:-pg}"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgresql-data:

networks:
  default:
